export enum AnalyticsEvents {
  get_otp_clicked = "web_get_otp_clicked",
  phone_verified = "web_phone_verified",
  sign_up_completed = "web_sign_up_completed",
  explore_more_clicked = "web_explore_more_clicked",
  rsvp_stream = "web_rsvp_stream",
  join_stream = "web_join_stream",
  livestream_opened = "web_livestream_opened",
  share_stream_url = "web_share_stream_url",
  connect_with_clicked = "web_connect_with_clicked",
  match_me_clicked = "web_match_me_clicked",
  profile_picure_added = "web_profile_picure_added",
  participant_joined_stream = "web_participant_joined_stream",
  subscribe_creator = "web_subscribe_creator",
  unsubscribe_creator = "web_unsubscribe_creator",
  rsvp_series = "web_rsvp_series",
  email_validation_failed = "web_email_validation_failed",
  rsvp_button_clicked = "web_rsvp_button_clicked",
  reward_card_clicked = "web_reward_card_clicked",
  livestream_reward_card_clicked = "web_livestream_reward_card_clicked",
  modal_placed_bid = "web_modal_placed_bid",
  card_payment_sucess = "web_card_payment_sucess",
  card_payment_error = "web_card_payment_error",
}
