const Watch = {
  v: "5.9.6",
  fr: 29.9700012207031,
  ip: 0,
  op: 90.0000036657751,
  w: 36,
  h: 36,
  nm: "watch",
  ddd: 0,
  assets: [
    {
      id: "image_0",
      w: 36,
      h: 36,
      u: "images/anims/watch/",
      p: "img_0.png",
      e: 0,
    },
  ],
  layers: [
    {
      ddd: 0,
      ind: 1,
      ty: 4,
      nm: "Shape Layer 1",
      sr: 1,
      ks: {
        o: { a: 0, k: 30, ix: 11 },
        r: { a: 0, k: 29, ix: 10 },
        p: {
          a: 1,
          k: [
            {
              i: { x: 0.833, y: 0.833 },
              o: { x: 0.167, y: 0.167 },
              t: 0,
              s: [-10, 22.75, 0],
              to: [10.958, 0, 0],
              ti: [-10.958, 0, 0],
            },
            { t: 30.0000012219251, s: [55.75, 22.75, 0] },
          ],
          ix: 2,
          l: 2,
        },
        a: { a: 0, k: [0, 0, 0], ix: 1, l: 2 },
        s: { a: 0, k: [68.653, 113.69, 100], ix: 6, l: 2 },
      },
      ao: 0,
      ef: [
        {
          ty: 28,
          nm: "Set Matte",
          np: 8,
          mn: "ADBE Set Matte3",
          ix: 1,
          en: 1,
          ef: [
            {
              ty: 10,
              nm: "Take Matte From Layer",
              mn: "ADBE Set Matte3-0001",
              ix: 1,
              v: { a: 0, k: 2, ix: 1 },
            },
            {
              ty: 7,
              nm: "Use For Matte",
              mn: "ADBE Set Matte3-0002",
              ix: 2,
              v: { a: 0, k: 4, ix: 2 },
            },
            {
              ty: 7,
              nm: "Invert Matte",
              mn: "ADBE Set Matte3-0003",
              ix: 3,
              v: { a: 0, k: 0, ix: 3 },
            },
            {
              ty: 7,
              nm: "If Layer Sizes Differ",
              mn: "ADBE Set Matte3-0004",
              ix: 4,
              v: { a: 0, k: 1, ix: 4 },
            },
            {
              ty: 7,
              nm: "Composite Matte with Original",
              mn: "ADBE Set Matte3-0005",
              ix: 5,
              v: { a: 0, k: 1, ix: 5 },
            },
            {
              ty: 7,
              nm: "Premultiply Matte Layer",
              mn: "ADBE Set Matte3-0006",
              ix: 6,
              v: { a: 0, k: 1, ix: 6 },
            },
          ],
        },
      ],
      shapes: [
        {
          ty: "gr",
          it: [
            {
              ty: "rc",
              d: 1,
              s: { a: 0, k: [11.357, 50.624], ix: 2 },
              p: { a: 0, k: [0, 0], ix: 3 },
              r: { a: 0, k: 0, ix: 4 },
              nm: "Rectangle Path 1",
              mn: "ADBE Vector Shape - Rect",
              hd: false,
            },
            {
              ty: "fl",
              c: { a: 0, k: [1, 1, 1, 1], ix: 4 },
              o: { a: 0, k: 100, ix: 5 },
              r: 1,
              bm: 0,
              nm: "Fill 1",
              mn: "ADBE Vector Graphic - Fill",
              hd: false,
            },
            {
              ty: "tr",
              p: { a: 0, k: [-8.071, -0.438], ix: 2 },
              a: { a: 0, k: [0, 0], ix: 1 },
              s: { a: 0, k: [100, 100], ix: 3 },
              r: { a: 0, k: 0, ix: 6 },
              o: { a: 0, k: 100, ix: 7 },
              sk: { a: 0, k: 0, ix: 4 },
              sa: { a: 0, k: 0, ix: 5 },
              nm: "Transform",
            },
          ],
          nm: "Rectangle 1",
          np: 3,
          cix: 2,
          bm: 0,
          ix: 1,
          mn: "ADBE Vector Group",
          hd: false,
        },
      ],
      ip: 0,
      op: 90.0000036657751,
      st: 0,
      ct: 1,
      bm: 0,
    },
    {
      ddd: 0,
      ind: 2,
      ty: 2,
      nm: "watch.png",
      cl: "png",
      refId: "image_0",
      sr: 1,
      ks: {
        o: { a: 0, k: 100, ix: 11 },
        r: { a: 0, k: 0, ix: 10 },
        p: { a: 0, k: [18, 18, 0], ix: 2, l: 2 },
        a: { a: 0, k: [18, 18, 0], ix: 1, l: 2 },
        s: { a: 0, k: [100, 100, 100], ix: 6, l: 2 },
      },
      ao: 0,
      ip: 0,
      op: 90.0000036657751,
      st: 0,
      bm: 0,
    },
  ],
  markers: [],
};

export default Watch;
